=== keerthimerugu6-max/Wipro-Project/XML_Assignments/StudentForm/Q10/classroom.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="classroom">

        <xs:complexType>

            <xs:sequence>

                <xs:element
                    name="student"
                    type="StudentDetails"
                    minOccurs="0"
                    maxOccurs="unbounded"/>

            </xs:sequence>

        </xs:complexType>

    </xs:element>


    <xs:complexType name="StudentDetails">

        <xs:sequence>

            <xs:element
                name="firstname"
                type="xs:string"/>

            <xs:element
                name="lastname"
                type="xs:string"/>

            <xs:element
                name="division"
                type="xs:string"/>

            <xs:element
                name="marks"
                type="xs:positiveInteger"/>

        </xs:sequence>


        <xs:attribute
            name="rollno"
            type="xs:positiveInteger"/>

    </xs:complexType>

</xs:schema>

=== keerthimerugu6-max/Wipro-Project/XML_Assignments/StudentForm/Q10/classroom.xml
<?xml version="1.0" encoding="UTF-8"?>

<classroom
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="classroom.xsd">

    <student rollno="1">

        <firstname>Rahul</firstname>

        <lastname>Sharma</lastname>

        <division>A</division>

        <marks>85</marks>

    </student>


    <student rollno="2">

        <firstname>Manju</firstname>

        <lastname>Kumar</lastname>

        <division>B</division>

        <marks>92</marks>

    </student>


    <student rollno="3">

        <firstname>Priya</firstname>

        <lastname>Patel</lastname>

        <division>A</division>

        <marks>78</marks>

    </student>

</classroom>
